"""add grammar_rules table (grammar dasar, Langkah 8)

Revision ID: 3e8d2c1a9b4f
Revises: 9f2b1c4a5d6e
Create Date: 2026-08-01 12:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e8d2c1a9b4f'
down_revision: Union[str, Sequence[str], None] = '9f2b1c4a5d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('example_translation', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_id', 'title', name='uq_grammar_lang_title')
    )
    op.create_index(op.f('ix_grammar_rules_language_id'), 'grammar_rules', ['language_id'], unique=False)
    op.create_index(op.f('ix_grammar_rules_title'), 'grammar_rules', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grammar_rules_title'), table_name='grammar_rules')
    op.drop_index(op.f('ix_grammar_rules_language_id'), table_name='grammar_rules')
    op.drop_table('grammar_rules')
    # ### end Alembic commands ###
