"""add phrases table (percakapan sehari-hari, Langkah 8)

Revision ID: 9f2b1c4a5d6e
Revises: d28290b68c50
Create Date: 2026-08-01 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2b1c4a5d6e'
down_revision: Union[str, Sequence[str], None] = 'd28290b68c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('context', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_id', 'phrase', 'context', name='uq_phrases_lang_phrase_context')
    )
    op.create_index(op.f('ix_phrases_language_id'), 'phrases', ['language_id'], unique=False)
    op.create_index(op.f('ix_phrases_phrase'), 'phrases', ['phrase'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrases_phrase'), table_name='phrases')
    op.drop_index(op.f('ix_phrases_language_id'), table_name='phrases')
    op.drop_table('phrases')
    # ### end Alembic commands ###
